//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceMinerthal
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", ConfigurationName="ServiceMinerthal.WSPEDIDOSERVICEPECASOAP")]
    public interface WSPEDIDOSERVICEPECASOAP
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw/ADDPEDIDOPECA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceMinerthal.ADDPEDIDOPECAResponse> ADDPEDIDOPECAAsync(ServiceMinerthal.ADDPEDIDOPECARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw/DELPEDIDOPECA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceMinerthal.DELPEDIDOPECAResponse> DELPEDIDOPECAAsync(ServiceMinerthal.DELPEDIDOPECARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw/GETPEDIDOKEYPECA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceMinerthal.GETPEDIDOKEYPECAResponse> GETPEDIDOKEYPECAAsync(ServiceMinerthal.GETPEDIDOKEYPECARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw/GETPEDIDOPECA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceMinerthal.GETPEDIDOPECAResponse> GETPEDIDOPECAAsync(ServiceMinerthal.GETPEDIDOPECARequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw")]
    public partial class TADDPEDIDOCAB
    {
        
        private string bANCOPEDIDOField;
        
        private string cONDICAOPAGAMENTOField;
        
        private string dATASPARCELAField;
        
        private string oBSPEDIDOField;
        
        private float pRECOFRETELIQField;
        
        private string tIPOFRETEField;
        
        private string tRANSPORTADORACLIENTEField;
        
        private TADDPEDIDODET[] tZITENSDOPEDIDOField;
        
        private string vLRPARCELAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BANCOPEDIDO
        {
            get
            {
                return this.bANCOPEDIDOField;
            }
            set
            {
                this.bANCOPEDIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CONDICAOPAGAMENTO
        {
            get
            {
                return this.cONDICAOPAGAMENTOField;
            }
            set
            {
                this.cONDICAOPAGAMENTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DATASPARCELA
        {
            get
            {
                return this.dATASPARCELAField;
            }
            set
            {
                this.dATASPARCELAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OBSPEDIDO
        {
            get
            {
                return this.oBSPEDIDOField;
            }
            set
            {
                this.oBSPEDIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public float PRECOFRETELIQ
        {
            get
            {
                return this.pRECOFRETELIQField;
            }
            set
            {
                this.pRECOFRETELIQField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TIPOFRETE
        {
            get
            {
                return this.tIPOFRETEField;
            }
            set
            {
                this.tIPOFRETEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TRANSPORTADORACLIENTE
        {
            get
            {
                return this.tRANSPORTADORACLIENTEField;
            }
            set
            {
                this.tRANSPORTADORACLIENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TADDPEDIDODET[] TZITENSDOPEDIDO
        {
            get
            {
                return this.tZITENSDOPEDIDOField;
            }
            set
            {
                this.tZITENSDOPEDIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string VLRPARCELA
        {
            get
            {
                return this.vLRPARCELAField;
            }
            set
            {
                this.vLRPARCELAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw")]
    public partial class TADDPEDIDODET
    {
        
        private string pERCCOMISSAOField;
        
        private string pRECOUNITARIOField;
        
        private string pRODUTOPEDIDOField;
        
        private string qUANTIDADEPRODUTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string PERCCOMISSAO
        {
            get
            {
                return this.pERCCOMISSAOField;
            }
            set
            {
                this.pERCCOMISSAOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string PRECOUNITARIO
        {
            get
            {
                return this.pRECOUNITARIOField;
            }
            set
            {
                this.pRECOUNITARIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PRODUTOPEDIDO
        {
            get
            {
                return this.pRODUTOPEDIDOField;
            }
            set
            {
                this.pRODUTOPEDIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=3)]
        public string QUANTIDADEPRODUTO
        {
            get
            {
                return this.qUANTIDADEPRODUTOField;
            }
            set
            {
                this.qUANTIDADEPRODUTOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw")]
    public partial class TSTATUSPEDIDO
    {
        
        private string bLOQCREDITOField;
        
        private string bLOQESTOQUEField;
        
        private string bLOQUEIOWMSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BLOQCREDITO
        {
            get
            {
                return this.bLOQCREDITOField;
            }
            set
            {
                this.bLOQCREDITOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BLOQESTOQUE
        {
            get
            {
                return this.bLOQESTOQUEField;
            }
            set
            {
                this.bLOQESTOQUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BLOQUEIOWMS
        {
            get
            {
                return this.bLOQUEIOWMSField;
            }
            set
            {
                this.bLOQUEIOWMSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw")]
    public partial class TGETPEDIDODET
    {
        
        private string aRMAZEMField;
        
        private string bLOQUEIOField;
        
        private string cFOPField;
        
        private System.DateTime dATAULTIMOFATURAMENTOField;
        
        private string dESCRICAOPRODUTOField;
        
        private string iTEMPEDIDOField;
        
        private string nOTAFISCALField;
        
        private float pRECOVENDAPRODUTOField;
        
        private string pRODUTOPEDIDOField;
        
        private string qUANTIDADEENTREGUEField;
        
        private string qUANTIDADELIBERADAField;
        
        private string qUANTIDADEPRODUTOField;
        
        private string sERIENFField;
        
        private string tIPODEENTRADASAIDAField;
        
        private TSTATUSPEDIDO tZSTATUSPEDIDOField;
        
        private string uNIDADEMEDIDAField;
        
        private float vALORTOTALDOPRODUTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ARMAZEM
        {
            get
            {
                return this.aRMAZEMField;
            }
            set
            {
                this.aRMAZEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BLOQUEIO
        {
            get
            {
                return this.bLOQUEIOField;
            }
            set
            {
                this.bLOQUEIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CFOP
        {
            get
            {
                return this.cFOPField;
            }
            set
            {
                this.cFOPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime DATAULTIMOFATURAMENTO
        {
            get
            {
                return this.dATAULTIMOFATURAMENTOField;
            }
            set
            {
                this.dATAULTIMOFATURAMENTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DESCRICAOPRODUTO
        {
            get
            {
                return this.dESCRICAOPRODUTOField;
            }
            set
            {
                this.dESCRICAOPRODUTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ITEMPEDIDO
        {
            get
            {
                return this.iTEMPEDIDOField;
            }
            set
            {
                this.iTEMPEDIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NOTAFISCAL
        {
            get
            {
                return this.nOTAFISCALField;
            }
            set
            {
                this.nOTAFISCALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public float PRECOVENDAPRODUTO
        {
            get
            {
                return this.pRECOVENDAPRODUTOField;
            }
            set
            {
                this.pRECOVENDAPRODUTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PRODUTOPEDIDO
        {
            get
            {
                return this.pRODUTOPEDIDOField;
            }
            set
            {
                this.pRODUTOPEDIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=9)]
        public string QUANTIDADEENTREGUE
        {
            get
            {
                return this.qUANTIDADEENTREGUEField;
            }
            set
            {
                this.qUANTIDADEENTREGUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=10)]
        public string QUANTIDADELIBERADA
        {
            get
            {
                return this.qUANTIDADELIBERADAField;
            }
            set
            {
                this.qUANTIDADELIBERADAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=11)]
        public string QUANTIDADEPRODUTO
        {
            get
            {
                return this.qUANTIDADEPRODUTOField;
            }
            set
            {
                this.qUANTIDADEPRODUTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string SERIENF
        {
            get
            {
                return this.sERIENFField;
            }
            set
            {
                this.sERIENFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string TIPODEENTRADASAIDA
        {
            get
            {
                return this.tIPODEENTRADASAIDAField;
            }
            set
            {
                this.tIPODEENTRADASAIDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public TSTATUSPEDIDO TZSTATUSPEDIDO
        {
            get
            {
                return this.tZSTATUSPEDIDOField;
            }
            set
            {
                this.tZSTATUSPEDIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string UNIDADEMEDIDA
        {
            get
            {
                return this.uNIDADEMEDIDAField;
            }
            set
            {
                this.uNIDADEMEDIDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public float VALORTOTALDOPRODUTO
        {
            get
            {
                return this.vALORTOTALDOPRODUTOField;
            }
            set
            {
                this.vALORTOTALDOPRODUTOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw")]
    public partial class TGETPEDIDOCAB
    {
        
        private string cODCLIENTEField;
        
        private string cODLOJACLIENTEField;
        
        private string cONDICAOPAGAMENTOField;
        
        private System.DateTime eMISSAOPEDIDOField;
        
        private string iSSINCLUIDOPRECOField;
        
        private string mOEDADOPEDIDOField;
        
        private string nOMEDOCLIENTEField;
        
        private string nUMPEDIDOVENDAField;
        
        private string tIPODECLIENTEField;
        
        private string tIPODEFRETEField;
        
        private string tIPODELIBERACAOPEDIDOField;
        
        private string tIPODEPEDIDOField;
        
        private string tRANSPORTADORACLIENTEField;
        
        private TGETPEDIDODET[] tZITENSDOPEDIDOField;
        
        private float tZVALORTOTALDOPEDIDOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CODCLIENTE
        {
            get
            {
                return this.cODCLIENTEField;
            }
            set
            {
                this.cODCLIENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CODLOJACLIENTE
        {
            get
            {
                return this.cODLOJACLIENTEField;
            }
            set
            {
                this.cODLOJACLIENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CONDICAOPAGAMENTO
        {
            get
            {
                return this.cONDICAOPAGAMENTOField;
            }
            set
            {
                this.cONDICAOPAGAMENTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime EMISSAOPEDIDO
        {
            get
            {
                return this.eMISSAOPEDIDOField;
            }
            set
            {
                this.eMISSAOPEDIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ISSINCLUIDOPRECO
        {
            get
            {
                return this.iSSINCLUIDOPRECOField;
            }
            set
            {
                this.iSSINCLUIDOPRECOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=5)]
        public string MOEDADOPEDIDO
        {
            get
            {
                return this.mOEDADOPEDIDOField;
            }
            set
            {
                this.mOEDADOPEDIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NOMEDOCLIENTE
        {
            get
            {
                return this.nOMEDOCLIENTEField;
            }
            set
            {
                this.nOMEDOCLIENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string NUMPEDIDOVENDA
        {
            get
            {
                return this.nUMPEDIDOVENDAField;
            }
            set
            {
                this.nUMPEDIDOVENDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string TIPODECLIENTE
        {
            get
            {
                return this.tIPODECLIENTEField;
            }
            set
            {
                this.tIPODECLIENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string TIPODEFRETE
        {
            get
            {
                return this.tIPODEFRETEField;
            }
            set
            {
                this.tIPODEFRETEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string TIPODELIBERACAOPEDIDO
        {
            get
            {
                return this.tIPODELIBERACAOPEDIDOField;
            }
            set
            {
                this.tIPODELIBERACAOPEDIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string TIPODEPEDIDO
        {
            get
            {
                return this.tIPODEPEDIDOField;
            }
            set
            {
                this.tIPODEPEDIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string TRANSPORTADORACLIENTE
        {
            get
            {
                return this.tRANSPORTADORACLIENTEField;
            }
            set
            {
                this.tRANSPORTADORACLIENTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=13)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TGETPEDIDODET[] TZITENSDOPEDIDO
        {
            get
            {
                return this.tZITENSDOPEDIDOField;
            }
            set
            {
                this.tZITENSDOPEDIDOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public float TZVALORTOTALDOPEDIDO
        {
            get
            {
                return this.tZVALORTOTALDOPEDIDOField;
            }
            set
            {
                this.tZVALORTOTALDOPEDIDOField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ADDPEDIDOPECA", WrapperNamespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", IsWrapped=true)]
    public partial class ADDPEDIDOPECARequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", Order=0)]
        public string CODIGOCLIENTE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", Order=1)]
        public string FILIALPEDIDO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", Order=2)]
        public string PEDIDOMAXIMA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", Order=3)]
        public ServiceMinerthal.TADDPEDIDOCAB TADDPEDIDO;
        
        public ADDPEDIDOPECARequest()
        {
        }
        
        public ADDPEDIDOPECARequest(string CODIGOCLIENTE, string FILIALPEDIDO, string PEDIDOMAXIMA, ServiceMinerthal.TADDPEDIDOCAB TADDPEDIDO)
        {
            this.CODIGOCLIENTE = CODIGOCLIENTE;
            this.FILIALPEDIDO = FILIALPEDIDO;
            this.PEDIDOMAXIMA = PEDIDOMAXIMA;
            this.TADDPEDIDO = TADDPEDIDO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ADDPEDIDOPECARESPONSE", WrapperNamespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", IsWrapped=true)]
    public partial class ADDPEDIDOPECAResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", Order=0)]
        public string ADDPEDIDOPECARESULT;
        
        public ADDPEDIDOPECAResponse()
        {
        }
        
        public ADDPEDIDOPECAResponse(string ADDPEDIDOPECARESULT)
        {
            this.ADDPEDIDOPECARESULT = ADDPEDIDOPECARESULT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DELPEDIDOPECA", WrapperNamespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", IsWrapped=true)]
    public partial class DELPEDIDOPECARequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", Order=0)]
        public string CODIGOCLIENTE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", Order=1)]
        public string FILIALPEDIDO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", Order=2)]
        public string NUMERODOPEDIDO;
        
        public DELPEDIDOPECARequest()
        {
        }
        
        public DELPEDIDOPECARequest(string CODIGOCLIENTE, string FILIALPEDIDO, string NUMERODOPEDIDO)
        {
            this.CODIGOCLIENTE = CODIGOCLIENTE;
            this.FILIALPEDIDO = FILIALPEDIDO;
            this.NUMERODOPEDIDO = NUMERODOPEDIDO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DELPEDIDOPECARESPONSE", WrapperNamespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", IsWrapped=true)]
    public partial class DELPEDIDOPECAResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", Order=0)]
        public string DELPEDIDOPECARESULT;
        
        public DELPEDIDOPECAResponse()
        {
        }
        
        public DELPEDIDOPECAResponse(string DELPEDIDOPECARESULT)
        {
            this.DELPEDIDOPECARESULT = DELPEDIDOPECARESULT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GETPEDIDOKEYPECA", WrapperNamespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", IsWrapped=true)]
    public partial class GETPEDIDOKEYPECARequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", Order=0)]
        public string CODIGOCLIENTE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", Order=1)]
        public string FILIALPEDIDO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DINICONSULTA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DFIMCONSULTA;
        
        public GETPEDIDOKEYPECARequest()
        {
        }
        
        public GETPEDIDOKEYPECARequest(string CODIGOCLIENTE, string FILIALPEDIDO, System.DateTime DINICONSULTA, System.DateTime DFIMCONSULTA)
        {
            this.CODIGOCLIENTE = CODIGOCLIENTE;
            this.FILIALPEDIDO = FILIALPEDIDO;
            this.DINICONSULTA = DINICONSULTA;
            this.DFIMCONSULTA = DFIMCONSULTA;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GETPEDIDOKEYPECARESPONSE", WrapperNamespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", IsWrapped=true)]
    public partial class GETPEDIDOKEYPECAResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ServiceMinerthal.TGETPEDIDOCAB[] GETPEDIDOKEYPECARESULT;
        
        public GETPEDIDOKEYPECAResponse()
        {
        }
        
        public GETPEDIDOKEYPECAResponse(ServiceMinerthal.TGETPEDIDOCAB[] GETPEDIDOKEYPECARESULT)
        {
            this.GETPEDIDOKEYPECARESULT = GETPEDIDOKEYPECARESULT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GETPEDIDOPECA", WrapperNamespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", IsWrapped=true)]
    public partial class GETPEDIDOPECARequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", Order=0)]
        public string CODIGOCLIENTE;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", Order=1)]
        public string FILIALPEDIDO;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", Order=2)]
        public string NUMERODOPEDIDO;
        
        public GETPEDIDOPECARequest()
        {
        }
        
        public GETPEDIDOPECARequest(string CODIGOCLIENTE, string FILIALPEDIDO, string NUMERODOPEDIDO)
        {
            this.CODIGOCLIENTE = CODIGOCLIENTE;
            this.FILIALPEDIDO = FILIALPEDIDO;
            this.NUMERODOPEDIDO = NUMERODOPEDIDO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GETPEDIDOPECARESPONSE", WrapperNamespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", IsWrapped=true)]
    public partial class GETPEDIDOPECAResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.0.5:9596/ws/wspedidoservicepeca.apw", Order=0)]
        public ServiceMinerthal.TGETPEDIDOCAB GETPEDIDOPECARESULT;
        
        public GETPEDIDOPECAResponse()
        {
        }
        
        public GETPEDIDOPECAResponse(ServiceMinerthal.TGETPEDIDOCAB GETPEDIDOPECARESULT)
        {
            this.GETPEDIDOPECARESULT = GETPEDIDOPECARESULT;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface WSPEDIDOSERVICEPECASOAPChannel : ServiceMinerthal.WSPEDIDOSERVICEPECASOAP, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class WSPEDIDOSERVICEPECASOAPClient : System.ServiceModel.ClientBase<ServiceMinerthal.WSPEDIDOSERVICEPECASOAP>, ServiceMinerthal.WSPEDIDOSERVICEPECASOAP
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSPEDIDOSERVICEPECASOAPClient() : 
                base(WSPEDIDOSERVICEPECASOAPClient.GetDefaultBinding(), WSPEDIDOSERVICEPECASOAPClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSPEDIDOSERVICEPECASOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSPEDIDOSERVICEPECASOAPClient(EndpointConfiguration endpointConfiguration) : 
                base(WSPEDIDOSERVICEPECASOAPClient.GetBindingForEndpoint(endpointConfiguration), WSPEDIDOSERVICEPECASOAPClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSPEDIDOSERVICEPECASOAPClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSPEDIDOSERVICEPECASOAPClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSPEDIDOSERVICEPECASOAPClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSPEDIDOSERVICEPECASOAPClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSPEDIDOSERVICEPECASOAPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceMinerthal.ADDPEDIDOPECAResponse> ServiceMinerthal.WSPEDIDOSERVICEPECASOAP.ADDPEDIDOPECAAsync(ServiceMinerthal.ADDPEDIDOPECARequest request)
        {
            return base.Channel.ADDPEDIDOPECAAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceMinerthal.ADDPEDIDOPECAResponse> ADDPEDIDOPECAAsync(string CODIGOCLIENTE, string FILIALPEDIDO, string PEDIDOMAXIMA, ServiceMinerthal.TADDPEDIDOCAB TADDPEDIDO)
        {
            ServiceMinerthal.ADDPEDIDOPECARequest inValue = new ServiceMinerthal.ADDPEDIDOPECARequest();
            inValue.CODIGOCLIENTE = CODIGOCLIENTE;
            inValue.FILIALPEDIDO = FILIALPEDIDO;
            inValue.PEDIDOMAXIMA = PEDIDOMAXIMA;
            inValue.TADDPEDIDO = TADDPEDIDO;
            return ((ServiceMinerthal.WSPEDIDOSERVICEPECASOAP)(this)).ADDPEDIDOPECAAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceMinerthal.DELPEDIDOPECAResponse> ServiceMinerthal.WSPEDIDOSERVICEPECASOAP.DELPEDIDOPECAAsync(ServiceMinerthal.DELPEDIDOPECARequest request)
        {
            return base.Channel.DELPEDIDOPECAAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceMinerthal.DELPEDIDOPECAResponse> DELPEDIDOPECAAsync(string CODIGOCLIENTE, string FILIALPEDIDO, string NUMERODOPEDIDO)
        {
            ServiceMinerthal.DELPEDIDOPECARequest inValue = new ServiceMinerthal.DELPEDIDOPECARequest();
            inValue.CODIGOCLIENTE = CODIGOCLIENTE;
            inValue.FILIALPEDIDO = FILIALPEDIDO;
            inValue.NUMERODOPEDIDO = NUMERODOPEDIDO;
            return ((ServiceMinerthal.WSPEDIDOSERVICEPECASOAP)(this)).DELPEDIDOPECAAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceMinerthal.GETPEDIDOKEYPECAResponse> ServiceMinerthal.WSPEDIDOSERVICEPECASOAP.GETPEDIDOKEYPECAAsync(ServiceMinerthal.GETPEDIDOKEYPECARequest request)
        {
            return base.Channel.GETPEDIDOKEYPECAAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceMinerthal.GETPEDIDOKEYPECAResponse> GETPEDIDOKEYPECAAsync(string CODIGOCLIENTE, string FILIALPEDIDO, System.DateTime DINICONSULTA, System.DateTime DFIMCONSULTA)
        {
            ServiceMinerthal.GETPEDIDOKEYPECARequest inValue = new ServiceMinerthal.GETPEDIDOKEYPECARequest();
            inValue.CODIGOCLIENTE = CODIGOCLIENTE;
            inValue.FILIALPEDIDO = FILIALPEDIDO;
            inValue.DINICONSULTA = DINICONSULTA;
            inValue.DFIMCONSULTA = DFIMCONSULTA;
            return ((ServiceMinerthal.WSPEDIDOSERVICEPECASOAP)(this)).GETPEDIDOKEYPECAAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceMinerthal.GETPEDIDOPECAResponse> ServiceMinerthal.WSPEDIDOSERVICEPECASOAP.GETPEDIDOPECAAsync(ServiceMinerthal.GETPEDIDOPECARequest request)
        {
            return base.Channel.GETPEDIDOPECAAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceMinerthal.GETPEDIDOPECAResponse> GETPEDIDOPECAAsync(string CODIGOCLIENTE, string FILIALPEDIDO, string NUMERODOPEDIDO)
        {
            ServiceMinerthal.GETPEDIDOPECARequest inValue = new ServiceMinerthal.GETPEDIDOPECARequest();
            inValue.CODIGOCLIENTE = CODIGOCLIENTE;
            inValue.FILIALPEDIDO = FILIALPEDIDO;
            inValue.NUMERODOPEDIDO = NUMERODOPEDIDO;
            return ((ServiceMinerthal.WSPEDIDOSERVICEPECASOAP)(this)).GETPEDIDOPECAAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSPEDIDOSERVICEPECASOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSPEDIDOSERVICEPECASOAP))
            {
                return new System.ServiceModel.EndpointAddress("http://remoto.minerthal.com.br:30014/WSPEDIDOSERVICEPECA.apw");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WSPEDIDOSERVICEPECASOAPClient.GetBindingForEndpoint(EndpointConfiguration.WSPEDIDOSERVICEPECASOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WSPEDIDOSERVICEPECASOAPClient.GetEndpointAddress(EndpointConfiguration.WSPEDIDOSERVICEPECASOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            WSPEDIDOSERVICEPECASOAP,
        }
    }
}
